example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
from django.urls import path, include
from .views import show_catalog

urlpatterns = [
    path('', show_catalog, name='show_catalog'),
]

mywatchlist/urls.py
from django.urls import path
from mywatchlist.views import show_watchlist, show_json, show_xml

app_name = 'mywatchlist'

urlpatterns = [
    path('html/', show_watchlist, name='show_watchlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('katalog', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

todolist/urls.py
from django.urls import path
from . import views

app_name = 'todolist'
urlpatterns = [
    path('', views.show_task, name='index'),
    path('json/', views.show_task_json, name='show_json'),
    path('create-task/', views.create, name='create-task'),
    path('add/', views.addTask, name='add-task'),
    path('register/', views.register, name='register'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('delete/<int:pk>/', views.delete, name='delete'),
]

example_app/models.py
from django.db import models

# Create your models here.

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models
import datetime

class MyWatchList(models.Model):
    watched = models.BooleanField(null=True)
    title = models.CharField(max_length=255)
    rating = models.IntegerField(blank=True, null=True)
    release_date = models.DateField(blank=True, default=datetime.date.today)
    review = models.TextField(blank=True, null=True)

    def __str__(self) -> str:
        return f"{self.title}"

todolist/models.py
from django.db import models
from django.contrib.auth.models import User

class Task(models.Model):
    user = models.ForeignKey(User, null=True, on_delete= models.SET_NULL)
    title = models.CharField(max_length=20)
    description = models.TextField()
    date = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self) -> str:
        return f"{self.id}. {self.title}"

todolist/forms.py
from django import forms

from todolist.models import Task

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = [
            'title',
            'description',
        ]

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from django.shortcuts import render
from katalog.models import CatalogItem

mhs_name = 'Maulana Bayu Risma Santoso Sari'
studentID = 2106750401

def show_catalog(req):
    data_catalog_item = CatalogItem.objects.all()
    context  = {
        'name' : mhs_name,
        'studentID': studentID,
        'list_item': data_catalog_item}
    return render(req, 'katalog.html', context)

mywatchlist/views.py
from django.shortcuts import render
from mywatchlist.models import MyWatchList
from django.http import HttpResponse
from django.core import serializers

mhs_name = 'Maulana Bayu Risma Santoso Sari'
studentID = 2106750401

def show_watchlist(req):
    data_watchlist = MyWatchList.objects.all()
    watched = list(filter(lambda x: x.watched == True, data_watchlist))
    # watched = MyWatchList.objects.filter(watched=True)
    context  = {
        'name' : mhs_name,
        'studentID': studentID,
        'watchlist': data_watchlist,
        'watched': len(watched),
        'unwatched': len(data_watchlist) - len(watched)
    }
    return render(req, 'watchlist.html', context)

def show_xml(req):
    data = MyWatchList.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(req):
    data = MyWatchList.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

todolist/views.py
from multiprocessing import context
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotFound
from django.core import serializers
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.contrib import messages
from django.urls import reverse
from .forms import TaskForm
from .models import Task
import datetime


@login_required(login_url='/todolist/login/')
def show_task(request):
    tasks = Task.objects.filter(user=request.user)
    context = {
        'page_title': 'To Do List',
        'tasks': tasks,
        'last_login': request.COOKIES['last_login'],
    }

    return render(request, 'todolist.html', context)

@login_required(login_url='/todolist/login/')
def show_task_json(request):
    tasks = Task.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", tasks))

def create(request):
    task_form = TaskForm()

    if request.method == 'POST':
        task_form = TaskForm(request.POST)
        form = task_form.save(commit=False)
        form.user = request.user
        form.save()

        return HttpResponseRedirect('/todolist/') 

    context = {
        'page_title': 'Create Task',
        'task_form': task_form
    }

    return render(request, 'create.html', context)

@login_required(login_url='/todolist/login/')
def addTask(request):
    if request.method == 'POST':
        title = request.POST.get("title")
        description = request.POST.get("description")

        new_task = Task(user=request.user, title=title, description=description)
        new_task.save()
        
        return HttpResponse(b"CREATED", status=201)
    return HttpResponseNotFound()

def register(request):
    form = UserCreationForm()

    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')

    context = {
        'page_title': 'Register new user',
        'form': form
    }

    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("todolist:index"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response
    
@login_required(login_url='/todolist/login/')
def delete(request, delete_id):
    if (Task.objects.get(pk=delete_id).user == request.user):
        Task.objects.filter(pk=delete_id).delete()
    return redirect("todolist:index")

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %} {% block content %}

<h1>Lab 1 Assignment PBP/PBD</h1>

<h3>Name: {{name}}</h3>

<h3>Student ID: {{studentID}}</h3>

<table>
  <tr>
    <th>Item Name</th>
    <th>Item Price</th>
    <th>Item Stock</th>
    <th>Rating</th>
    <th>Description</th>
    <th>Item URL</th>
  </tr>
  {% comment %} Add the data below this line {% endcomment %} {% for item in list_item %}
  <tr>
    <th>{{item.item_name}}</th>
    <th>{{item.item_price}}</th>
    <th>{{item.item_stock}}</th>
    <th>{{item.description}}</th>
    <th>{{item.rating}}</th>
    <th><a href="{{item.item_url}}">{{item.item_url}}</a></th>
  </tr>
  {% endfor %}
</table>

{% endblock content %}

mywatchlist/templates/watchlist.html
{% extends 'base.html' %} {% block content %}

<h1>My Watchlist</h1>

<h3>Name: {{name}}</h3>

<h3>Student ID: {{studentID}}</h3>

<table>
  {% if watched >= unwatched %}
  <h2 style="text-align: center">Selamat, kamu sudah banyak menonton!</h2>
  {% else %}
  <h2 style="text-align: center">Wah, kamu masih sedikit menonton!</h2>
  {% endif %}

  <tr>
    <th>No</th>
    <th>Watched</th>
    <th>Title</th>
    <th>Rating</th>
    <th>Release Date</th>
    <th>Review</th>
  </tr>
  {% comment %} Add the data below this line {% endcomment %} {% for item in watchlist %}
  <tr>
    <th>{{item.id}}</th>
    <th>{{item.watched}}</th>
    <th>{{item.title}}</th>
    <th>{{item.rating}}</th>
    <th>{{item.release_date}}</th>
    <th>{{item.review}}</th>
  </tr>
  {% endfor %}
</table>

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block meta %} {% endblock meta %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous" />
    <link rel="icon" href="data:;base64,iVBORw0KGgo=" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  </head>

  <body>
    {% block content %} {% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script>
  </body>
</html>

todolist/templates/create.html
{% extends 'base.html' %} {% block meta %}
<title>{{page_title}}</title>
<style>
  form {
    position: absolute;
    top: 45%;
    left: 50%;
    transform: translate(-50%, -50%);
    margin-top: 50px;
    padding: 25px;
    background-color: khaki;
    -webkit-box-shadow: 2px 2px 13px -4px rgba(0, 0, 0, 0.21);
    box-shadow: 2px 2px 13px -4px rgba(0, 0, 0, 0.21);
    border-radius: 15px;
    max-width: 500px;
  }
</style>
{% endblock meta %} {% block content %}

<form method="POST">
  <h1 style="text-align: center">{{page_title}}</h1>
  {% csrf_token %}
  <table>
    {{task_form.as_table}}
  </table>
  <input style="text-align: center" class="btn login_btn btn-secondary" type="submit" name="submit" value="Create" />
</form>

{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<title>Login</title>
<link rel="stylesheet" href="{% static 'todolist/css/login.css' %}" />

{% endblock meta %} {% block content %}
<body>
  <div class="center">
    <h1>Login</h1>
    <form method="POST" action="">
      {% csrf_token %}
      <div class="field">
        <input type="text" name="username" required />
        <label for="username">Username</label>
        <span></span>
      </div>
      <div class="field">
        <input type="password" name="password" required />
        <label for="password">Password</label>
        <span></span>
      </div>
      <input class="btn login_btn btn-secondary" type="submit" value="Login" />
      <div class="signup-link">Belum mempunyai akun? <a href="{% url 'todolist:register' %}">Buat Akun</a></div>
    </form>

    {% if messages %}
    <ul>
      {% for message in messages %}
      <li>{{ message }}</li>
      {% endfor %}
    </ul>
    {% endif %}
  </div>
</body>

{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<title>{{page_title}}</title>
<link rel="stylesheet" href="{% static 'todolist/css/register.css' %}" />
{% endblock meta %} {% block content %}

<form method="POST" action="">
  <h1>{{page_title}}</h1>
  {% csrf_token %}
  <table>
    {{form.as_table}}
  </table>
  <input style="text-align: center" class="btn login_btn btn-secondary" type="submit" name="submit" value="Register" />
</form>

{% if messages %}
<ul>
  {% for message in messages %}
  <li>{{ message }}</li>
  {% endfor %}
</ul>
{% endif %} {% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<title>{{page_title}}</title>
<link rel="stylesheet" href="{% static 'todolist/css/index.css' %}" />

{% endblock meta %} {% block content %}
<script>
  window.CSRF_TOKEN = '{{csrf_token}}';
</script>

<div class="header-bar">
  <div>
    <h3>Hello {{request.user}}</h3>
  </div>
  <div>
    <a class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#staticBackdrop">Add New Task</a>
    <a class="btn btn-outline-primary btn-sm" href="{% url 'todolist:logout' %}">Logout</a>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="staticBackdropLabel">New Task</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form id="form" onsubmit="return false;">
          {% csrf_token %}
          <div class="mb-3">
            <label for="InputTitle" class="form-label">Title</label>
            <input type="text" class="form-control" id="InputTitle" />
          </div>
          <div class="mb-3">
            <label for="InputDeskripsi" class="form-label">Deskripsi</label>
            <input type="text" class="form-control" id="InputDeskripsi" />
          </div>
          <button type="submit" class="btn btn-primary" id="submitForm">Submit</button>
        </form>
      </div>
    </div>
  </div>
</div>

<main class="grid"></main>

<script>

  function getTask() {
    fetch("{% url 'todolist:show_json' %}")
      .then((res) => res.json())
      .then((data) => {
        let htmlString = '';
        data.forEach((value) => {
          htmlString += `<article>
            <h3>${value.fields.title}</h3>
            <p>${value.fields.description}</p>
            <button type="submit" class="btn btn-danger btn-sm delete-item" data-item="${value.pk}">Delete</button>
        </article>`;
        });
        document.querySelector('.grid').innerHTML = htmlString;
      });
  }
  
  $(document).ready(function () {
    $('#form').submit(function (e) {
      // preventing from page reload and default actions
      e.preventDefault();
      var title = $('#InputTitle').val();
      var description = $('#InputDeskripsi').val();
      
      // make POST ajax call
      $.ajax({
        method: 'POST',
        url: "add/",
        headers: {"X-CSRFToken": window.CSRF_TOKEN},
        data: {
          title: title,
          description: description,
        },
        success: function (response) {
          // clear the form.
          $('#form').trigger('reset');
          
          $('#staticBackdrop').modal('hide');
          $('.modal-backdrop').remove();
          getTask()
        },
        error: function (xhr, errmsg, err) {
          // alert the error if any error occured
          console.log(xhr.status + ": " + xhr.responseText);
        },
      });
    });
  })
  
  getTask()
</script>
{% endblock content %}